name: Unit Test
run-name: Home Station pipelines for building and running unit tests
on:
  push:
    branches:
      - main
jobs:
  build_and_run_unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -yq build-essential cmake gcc git ninja-build python3-venv
      - name: Install gcovr in venv
        run: |
          python3 -m venv venv
          ./venv/bin/pip install gcovr
      - name: Get third-party dependencies
        run: |
          git submodule update --init --recursive
      - name: Configure test suite
        run: |
          cmake --preset test
      - name: Build test suite
        run: |
          cmake --build --preset test
      - name: Run test suite
        run: |
          ctest -V --test-dir build/test
      - name: Launch code coverage
        run: |
          ./venv/bin/gcovr -r . --filter "src" --html-details -o build/test/code_coverage.html
      - name: Archive code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ${{ github.workspace }}/build/test/code_coverage.html
